---

default_install_hook_types: [pre-commit, commit-msg]
default_stages: [pre-commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: requirements-txt-fixer
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.7.0-1
    hooks:
      - id: shfmt-docker
        args: [-i, '4', -w, -l]
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.9.0
    hooks:
      - id: shellcheck
        args: [-f, gcc]
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.13
    hooks:
      - id: validate-pyproject
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.278
    hooks:
      - id: ruff
        args: [-v, --fix, --show-fixes, --exit-non-zero-on-fix]
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        args: [-v]
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.35.0
    hooks:
      - id: markdownlint-fix-docker
        name: markdownlint
        args: [-c, .ci/markdownlint.jsonc]
        exclude: CHANGELOG.md
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.32.0
    hooks:
      - id: yamllint
        args: [--strict, -c=.ci/yamllint.yml]
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
        name: gitlint
        args: [--config, .ci/gitlint.ini, --staged, --msg-filename]
      - id: gitlint-ci
        name: gitlint-ci
        args: [--config, .ci/gitlint.ini]
  - repo: https://github.com/aanatoly/check-changelog
    rev: '0.3.0'
    hooks:
      - id: check-changelog
